name: Pixel Vision 8

on:
  push:
    branches: 'v**'

jobs:

  # This runs before the builds and creates the new feature release
  create-release:

    name: "Create Release"
    runs-on: "ubuntu-latest"

    # Steps for the task
    steps:

      # Figure out what the next tag should be
      - id: compute_tag
        uses: craig-day/compute-tag@v10
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: patch

      # Create the new release tag based on the above tag value and pass in the generated change log
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.compute_tag.outputs.next_tag }}
          release_name: Pixel Vision 8 ${{ steps.compute_tag.outputs.next_tag }} Release
          draft: false
          prerelease: true

  changelogger:
    runs-on: ubuntu-latest
    needs: create-release

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      # Figure out what the CURRENT tag should be
      - id: compute_tag
        uses: craig-day/compute-tag@v10
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: patch

      - name: save Changelog
        id: PREVIOUS_version
        run: |
          IFS='.' read -ra my_array <<< "${{ steps.compute_tag.outputs.next_tag }}"
          echo "CURRENT=${my_array[0]:1}.${my_array[1]}.$((${my_array[2]} - 1))" >> $GITHUB_ENV
          echo "PREVIOUS=${my_array[0]:1}.${my_array[1]}.$((${my_array[2]} - 2))" >> $GITHUB_ENV

      - name: Create Changelog
        id: changelog
        uses: jimschubert/beast-changelog-action@v1
        with:
          FROM: v${{ env.PREVIOUS }}
          TO: v${{ env.CURRENT }}

      - name: View Changelog
        run: cat .github/CHANGELOG.md

      # Update the release with the change log
      - name: Update Release
        id: update_release
        uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          tag: v${{env.CURRENT}}
          gzip: false
          body: "$(cat .github/CHANGELOG.md)"
